### ISSUE TITLE
rewrite to-do

### ISSUE THREAD

**Issue by mpsparrow** [mpsparrow/applesauce#75]
### Framework
- [ ] #81 add an "always enabled" variable for plugins
- [ ] #82 create defaults for plugininfo.py variables that are not defined instead of requiring the variables to be there
- [ ] #105 add plugin.ini

### Plugins
- [ ] #85 create archiving plugin
- [ ] #91 create moderation plugin (ban, kick, clear, tempban?)

### Other
- [ ] #95 update GitHub wiki

### Not Possible/Not Worth?
- [ ] #96 look into rewriting so that enabling and disabling plugin checking can be done at an `on_command` level
- [ ] #110 strawpoll (that is secure against spam)

### Lauchmelder
- [x] #108 optimize resource usage
- [x] #99 make flag trivia
- [x] #87 port over any other old commands (8ball, rate, etc) into plugin(s)
- [x] select, enable/disable and stuff through emoji reactions in plugin embed
- [x] tabbed navigation for embeds (specifically plugin embeds)
- [x] #88 create wolfram alpha plugin
- [x] #89 create wikipedia plugin

### mattthetechguy
- [x] #93 make a custom command generator plugin
- [x] #94 make sure all commands have proper cooldowns
- [x] #83 create leaderboard system plugin
- [x] #84 create a proper working help plugin
- [x] #100 keyerror in Plugin Management plugin
- [x] #98 ignore invalid plugin folders
- [x] #90 make tabbed plugin embed work properly on multiple guilds
- [x] add in custom prefixes
- [x] create a collection which logs guild specific information (prefix, name, guildid, joined date, etc)
- [x] create separate file for plugin details and variables (this way they don't error out and become unreachable if the main plugin errors out)
- [x] make sure loading of plugins produce and log a proper error
